[package]
name = "logics"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.13.0"
bevy_prototype_lyon = "0.11.0"
bevy-inspector-egui = "=0.23.0"
bevy_pancam = "0.11.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3