[package]
name = "logics"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9.1"
bevy_prototype_lyon = "0.7.2"
bevy-inspector-egui = "0.17.0"
bevy_pancam = "0.7.0"