[package]
name = "logics"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"
bevy_prototype_lyon = "0.12.0"
bevy-inspector-egui = "0.25.1"
bevy_pancam = "0.13.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3